// Original generated practice content. It is an interface fixture, not a rehearsal score.
export const practiceMusicXml = `<?xml version="1.0" encoding="UTF-8"?>
<score-partwise version="4.0"><work><work-title>Evening practice</work-title></work><part-list>${['Soprano','Alto','Tenor','Bass'].map((name,index)=>`<score-part id="P${index+1}"><part-name>${name}</part-name><score-instrument id="I${index+1}"><instrument-name>Choir</instrument-name></score-instrument><midi-instrument id="I${index+1}"><midi-channel>${index+1}</midi-channel><midi-program>53</midi-program></midi-instrument></score-part>`).join('')}</part-list>${['Soprano','Alto','Tenor','Bass'].map((name,part)=>`<part id="P${part+1}">${Array.from({length:16},(_,measure)=>`<measure number="${measure+1}">${measure===0?`<attributes><divisions>4</divisions><key><fifths>0</fifths></key><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>${part===3?'F':'G'}</sign><line>${part===3?'4':'2'}</line></clef></attributes><direction><direction-type><metronome><beat-unit>quarter</beat-unit><per-minute>96</per-minute></metronome></direction-type><sound tempo="96"/></direction>`:''}${Array.from({length:4},(_,beat)=>`<note><pitch><step>${['C','D','E','G'][(measure+beat+part)%4]}</step><octave>${part>1?3:4}</octave></pitch><duration>4</duration><type>quarter</type><lyric><text>la</text></lyric></note>`).join('')}</measure>`).join('')}</part>`).join('')}</score-partwise>`;
export function practiceWave() {
  const rate=8000, samples=rate*20, bytes=Buffer.alloc(44+samples*2);
  bytes.write('RIFF'); bytes.writeUInt32LE(bytes.length-8,4); bytes.write('WAVEfmt ',8); bytes.writeUInt32LE(16,16); bytes.writeUInt16LE(1,20); bytes.writeUInt16LE(1,22); bytes.writeUInt32LE(rate,24); bytes.writeUInt32LE(rate*2,28); bytes.writeUInt16LE(2,32); bytes.writeUInt16LE(16,34); bytes.write('data',36); bytes.writeUInt32LE(samples*2,40);
  for(let i=0;i<samples;i++) bytes.writeInt16LE(Math.round(Math.sin(i/rate*2*Math.PI*220)*1200),44+i*2);
  return bytes;
}
