import assert from "node:assert/strict";
import test from "node:test";
import { chromium, webkit, expect } from "@playwright/test";
import { startStorageFixture } from "./storage-fixture.mjs";

for (const [engine, browserType] of [["chromium", chromium], ["webkit", webkit]]) {
  test(`real Worker attachments: create, edit, import, preview and restore (${engine})`, { timeout: 120_000 }, async t => {
    const fixture = await startStorageFixture({ authenticated: true, previewEntry: false });
    let browser;
    t.after(async () => { try { await browser?.close(); } finally { await fixture.stop(); } });
    browser = await browserType.launch();
    const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
    const account = fixture.accounts[0];
    assert.equal((await context.request.post(`${fixture.origin}/api/auth/sign-in/email`, { headers: { origin: fixture.origin }, data: { email: account.email, password: account.password } })).status(), 200);
    const page = await context.newPage();
    const errors = []; page.on("pageerror", error => errors.push(error.message));
    const url = `${fixture.origin}/choirs/${fixture.choirId}`;
    const api = `${fixture.origin}/api/choirs/${fixture.choirId}`;
    const openMenu = () => page.getByRole("button", { name: "本地链路测试 更多操作", exact: true }).click();
    const addAttachment = async kind => {
      await openMenu(); await page.getByRole("menuitem", { name: "添加附件", exact: true }).click();
      await page.getByRole("button", { name: kind, exact: true }).click();
    };
    const secondUpload = await context.request.post(api + "/scores", { multipart: { file: { name: "另一份乐谱.pdf", mimeType: "application/pdf", buffer: fixture.pdf } } });
    assert.equal(secondUpload.status(), 201);
    const secondScore = (await secondUpload.json()).score;
    assert.equal((await context.request.post(`${api}/scores/${secondScore.id}/attachments/links`, { data: { id: crypto.randomUUID(), name: "另一首的参考", url: "https://example.org/second" } })).status(), 201);
    await page.goto(url);
    await expect(page.getByRole("checkbox", { name: "显示全部附件" })).toHaveCount(0);
    await openMenu();
    await expect(page.getByRole("menuitem", { name: "文件信息", exact: true })).toHaveCount(0);
    await expect(page.getByRole("menuitem", { name: "历史 PDF 版本", exact: true })).toHaveCount(0);
    await expect(page.getByRole("menuitem", { name: "添加链接", exact: true })).toHaveCount(0);
    await page.getByRole("menuitem", { name: "添加附件", exact: true }).click();
    await page.getByRole("button", { name: "音频", exact: true }).click();
    await expect(page.getByLabel("选择附件文件")).toHaveAttribute("accept", ".mp3,.m4a,.aac,.wav,.flac,.ogg,.opus");
    await page.getByRole("button", { name: "返回附件类型", exact: true }).click();
    await page.getByRole("button", { name: "文档（仅 .md）", exact: true }).click();
    await page.getByRole("button", { name: "直接编写", exact: true }).click();
    await page.locator('[contenteditable="true"]').fill("统一元音，轻声进入。");
    await page.getByRole("button", { name: "保存", exact: true }).click();
    await expect(page.getByRole("button", { name: "编辑", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "关闭", exact: true }).click();
    const scoreAttachments = page.getByRole("button", { name: /^本地链路测试：\d+ 个附件$/ });
    const secondAttachments = page.getByRole("button", { name: "另一份乐谱：1 个附件", exact: true });
    await expect(scoreAttachments).toBeVisible();
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toHaveCount(0);
    await scoreAttachments.click();
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: "另一首的参考", exact: true })).toHaveCount(0);
    await expect(scoreAttachments).toHaveAttribute("aria-expanded", "true");
    await secondAttachments.click();
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toBeVisible();
    await expect(page.getByRole("link", { name: "另一首的参考", exact: true })).toBeVisible();
    await scoreAttachments.click();
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toHaveCount(0);
    await expect(scoreAttachments).toHaveAttribute("aria-expanded", "false");
    await expect(page.getByRole("link", { name: "另一首的参考", exact: true })).toBeVisible();
    await secondAttachments.click();
    await expect(page.getByRole("link", { name: "另一首的参考", exact: true })).toHaveCount(0);
    await scoreAttachments.click();
    await page.getByRole("button", { name: "排练笔记.md", exact: true }).click();
    await expect(page.getByRole("dialog")).toContainText("统一元音，轻声进入。");
    await expect(page.getByRole("dialog").getByRole("link", { name: /下载/ })).toHaveCount(0);
    await expect(page.getByRole("dialog").getByRole("button", { name: /下载/ })).toHaveCount(0);
    await page.getByRole("button", { name: "编辑", exact: true }).click();
    await page.locator('[contenteditable="true"]').fill("结尾渐弱，听指挥收音。");
    await expect(page.getByRole("button", { name: /下载/ })).toHaveCount(0);
    await page.getByRole("button", { name: "文档更多操作", exact: true }).click();
    const draftEvent = page.waitForEvent("download");
    await page.getByRole("menuitem", { name: "下载草稿 .md", exact: true }).click();
    assert.equal((await draftEvent).suggestedFilename(), "排练笔记.md");
    await page.getByRole("button", { name: "关闭", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "处理未保存的修改" })).toBeVisible();
    await page.getByRole("button", { name: "继续编辑", exact: true }).click();
    await page.getByRole("button", { name: "保存", exact: true }).click();
    await expect(page.getByRole("button", { name: "编辑", exact: true })).toBeVisible();
    await page.getByRole("button", { name: "关闭", exact: true }).click();
    await page.getByRole("button", { name: "排练笔记.md 更多操作", exact: true }).click();
    const downloadEvent = page.waitForEvent("download");
    await page.getByRole("menuitem", { name: "下载", exact: true }).click();
    assert.equal((await downloadEvent).suggestedFilename(), "排练笔记.md");
    await page.reload();
    await expect(scoreAttachments).toHaveAttribute("aria-expanded", "false");
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toHaveCount(0);
    await scoreAttachments.click();
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toBeVisible();

    await addAttachment("PDF");
    await expect(page.getByLabel("选择附件文件")).toHaveAttribute("accept", ".pdf");
    await page.getByLabel("选择附件文件").setInputFiles({ name: "歌词译文.pdf", mimeType: "application/pdf", buffer: fixture.pdf });
    await page.getByRole("button", { name: "上传", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.getByRole("button", { name: "歌词译文.pdf", exact: true }).click();
    await expect(page.locator(".pdfViewer .page").first()).toContainText("SAME PAGE VISUAL FIXTURE");
    await expect(page.getByRole("dialog").getByRole("link", { name: /下载/ })).toHaveCount(0);
    await expect(page.getByRole("dialog").getByRole("button", { name: /下载/ })).toHaveCount(0);
    await page.getByRole("button", { name: "下一页", exact: true }).click();
    await expect(page.locator(".attachment-pdf-toolbar")).toContainText("2 / 2");
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.getByRole("button", { name: "关闭", exact: true }).click();

    await addAttachment("文档（仅 .md）");
    await expect(page.getByLabel("选择附件文件")).toHaveAttribute("accept", ".md");
    await page.getByLabel("选择附件文件").setInputFiles({ name: "补充说明.md", mimeType: "text/markdown", buffer: Buffer.from("# 补充说明\n\n上传的文字保持可编辑。") });
    await page.getByRole("button", { name: "上传", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await page.getByRole("button", { name: "补充说明.md", exact: true }).click();
    await expect(page.getByRole("dialog")).toContainText("上传的文字保持可编辑。");
    await page.getByRole("button", { name: "关闭", exact: true }).click();

    await addAttachment("链接");
    await page.getByLabel("网址", { exact: true }).fill("https://example.org/rehearsal");
    await page.getByRole("button", { name: "返回附件类型", exact: true }).click();
    await expect(page.getByRole("dialog", { name: "处理未保存的修改" })).toBeVisible();
    await page.getByRole("button", { name: "继续编辑", exact: true }).click();
    await expect(page.getByLabel("网址", { exact: true })).toHaveValue("https://example.org/rehearsal");
    await page.getByRole("button", { name: "添加", exact: true }).click();
    await expect(page.getByRole("link", { name: "example.org", exact: true })).toHaveAttribute("href", "https://example.org/rehearsal");

    await page.getByRole("button", { name: "歌词译文.pdf 更多操作", exact: true }).click();
    await page.getByRole("menuitem", { name: "移到回收站", exact: true }).click();
    await page.getByRole("button", { name: "移到回收站", exact: true }).click();
    await expect(page.getByRole("dialog")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "排练笔记.md", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "歌词译文.pdf", exact: true })).toHaveCount(0);
    await page.goto(url + "/settings/trash");
    await page.getByRole("button", { name: "恢复", exact: true }).click();
    // A click dispatches the mutation; leaving before its refreshed row disappears
    // can cancel the actual restore request during full-document navigation.
    await expect(page.getByRole("button", { name: "恢复", exact: true })).toHaveCount(0);
    await page.goto(url);
    await scoreAttachments.click();
    await expect(page.getByRole("button", { name: "歌词译文.pdf", exact: true })).toBeVisible();

    const list = await (await context.request.get(`${api}/attachments?scoreIds=${fixture.scoreId}`)).json();
    assert.equal(list.attachments.length, 4);
    const markdown = list.attachments.find(item => item.name === "排练笔记.md");
    const saved = await context.request.get(`${api}/scores/${fixture.scoreId}/attachments/${markdown.id}/file`);
    assert.match(await saved.text(), /结尾渐弱，听指挥收音/);
    assert.equal((await (await context.request.get(api + "/scores")).json()).scores.length, 2);
    assert.deepEqual(errors, []);
  });
}
